#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Mon Jun 08 16:25:54 CST 2026
maven-metadata-aliyun-maven.xml/@default-aliyun-maven-https\://maven.aliyun.com/repository/public/.lastUpdated=1780907154483
maven-metadata-aliyun-maven.xml.error=Could not transfer metadata org.jetbrains.kotlin/maven-metadata.xml from/to aliyun-maven (https\://maven.aliyun.com/repository/public)\: Permission denied\: no further information
