#NOTE: This is a Maven Resolver internal implementation file, its format can be changed without prior notice.
#Thu May 07 10:59:57 CST 2026
maven-metadata-aliyun-maven.xml/@default-aliyun-maven-https\://maven.aliyun.com/repository/public/.lastUpdated=1778122797017
maven-metadata-aliyun-maven.xml.error=Could not transfer metadata org.cyclonedx/maven-metadata.xml from/to aliyun-maven (https\://maven.aliyun.com/repository/public)\: Permission denied\: no further information
